name: Code style check

on: [push]

jobs:
  check:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 15.4
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
    - name: Check SwiftFromat
      run: swift run swiftformat . --lint
